name: check
on:
  push:
    branches-ignore:
    - bump-*
  pull_request: {}

jobs:
  check:
    runs-on: macos-latest
    permissions:
      contents: 'read'

    steps:
    - uses: actions/checkout@v2
    - run: hooks/pre-commit
      env:
        HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
